import Head from 'next/head';
import { useState } from "react";


export default function Home() {
    const [value,setValue] = useState("")

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 >
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
          <input onChange={(e) => setValue(e.target.value)} value={value} placeholder="Search..."></input>
        </div>

    </main>
    </div>
  );
}
